'use strict';

export const mok = [
    {
        consultId: 'test2_2022-04-07T11:21:48.618',
        createId: 'test2',
        consultChannel: 2,
        consultChannelName: '소견요청 협진',
        deadlineDatetime: null,
        startDatetime: '2022-04-05 13:50:00',
        endDatetime: '2022-04-12 14:50:00',
        measurementCode: null,
        caseInfoList: [
            {
                consultId: 'test2_2022-04-07T11:21:48.618',
                orderNo: 1,
                caseTitle: '김입원 환자의 대장암 수술 이후',
                caseContents: '보건복지부장관은 전자의무기록이 효율적이고',
                patientId: 'patient2',
                patientName: '환자2',
                patientAge: 53,
                patientWard: '208',
                patientWardRoom: '2308',
                patientCondition: '2',
                patientGender: 'M',
                measurementCode: null,
            },
        ],
        memberInfoList: [
            {
                consultId: 'test2_2022-04-07T11:21:48.618',
                orderNo: 1,
                doctorId: 'ryan',
                doctorName: 'drcha',
                doctorLevel: 0,
                doctorLevelName: '교수님',
                replyState: null,
                doctorClass: 0,
                doctorClassName: '일반외과',
                remoteState: 'N',
            },
        ],
    },
    {
        consultId: 'etest1_2022-04-19T10:20:39.031',
        createId: 'etest1',
        consultChannel: 5,
        consultChannelName: '응급협진 요청',
        deadlineDatetime: null,
        startDatetime: '2022-03-08 10:20:00',
        endDatetime: null,
        measurementCode: 'SEERS_2111011004_VRTO',
        caseInfoList: [
            {
                consultId: 'etest1_2022-04-19T10:20:39.031',
                orderNo: 1,
                caseTitle: '뇌졸증 환자',
                caseContents: '',
                patientId: 'epatient1',
                patientName: '응급환자',
                patientAge: 53,
                patientWard: null,
                patientWardRoom: null,
                patientCondition: null,
                patientGender: 'M',
                measurementCode: null,
            },
        ],
        memberInfoList: [
            {
                consultId: 'etest1_2022-04-19T10:20:39.031',
                orderNo: 1,
                doctorId: 'test1',
                doctorName: '의사1',
                doctorLevel: 0,
                doctorLevelName: '교수님',
                replyState: null,
                doctorClass: 0,
                doctorClassName: '일반외과',
                remoteState: 'N',
            },
            {
                consultId: 'etest1_2022-04-19T10:20:39.031',
                orderNo: 2,
                doctorId: 'test2',
                doctorName: '의사2',
                doctorLevel: 0,
                doctorLevelName: '교수님',
                replyState: null,
                doctorClass: 0,
                doctorClassName: '일반외과',
                remoteState: 'N',
            },
        ],
    },
    {
        consultId: 'test3_2022-03-24T15:58:48.839',
        createId: 'test3',
        consultChannel: 3,
        consultChannelName: '실시간 원격 협진',
        deadlineDatetime: null,
        startDatetime: '2022-03-11 13:50:00',
        endDatetime: '2022-03-11 14:50:00',
        measurementCode: null,
        caseInfoList: [
            {
                consultId: 'test3_2022-03-24T15:58:48.839',
                orderNo: 1,
                caseTitle: '김입원 환자의 대장암 수술 이후',
                caseContents: '보건복지부장관은 전자의무기록이 효율적이고',
                patientId: 'patient_2',
                patientName: '환자2',
                patientAge: 53,
                patientWard: '208',
                patientWardRoom: '2308',
                patientCondition: '2',
                patientGender: 'M',
                measurementCode: null,
            },
        ],
        memberInfoList: [
            {
                consultId: 'test3_2022-03-24T15:58:48.839',
                orderNo: 1,
                doctorId: 'test1',
                doctorName: '의사1',
                doctorLevel: 0,
                doctorLevelName: '교수님',
                replyState: null,
                doctorClass: 0,
                doctorClassName: '일반외과',
                remoteState: 'N',
            },
            {
                consultId: 'test3_2022-03-24T15:58:48.839',
                orderNo: 2,
                doctorId: 'test2',
                doctorName: '의사2',
                doctorLevel: 0,
                doctorLevelName: '교수님',
                replyState: null,
                doctorClass: 0,
                doctorClassName: '일반외과',
                remoteState: 'N',
            },
        ],
    },
    {
        consultId: null,
        createId: '',
        consultChannel: 4,
        consultChannelName: '선별진료',
        deadlineDatetime: '',
        startDatetime: '2022-02-16 10:57:44',
        endDatetime: '',
        measurementCode: null,
        caseInfoList: [
            {
                consultId: null,
                orderNo: 0,
                caseTitle: null,
                caseContents: null,
                patientId: '0000',
                patientName: 'test1',
                patientAge: 40,
                patientWard: null,
                patientWardRoom: null,
                patientCondition: null,
                patientGender: 'M',
                measurementCode: null,
            },
        ],
        memberInfoList: null,
    },
];

export const consultAlarmList = [
    {
        consultId: 'test2_2022-03-08T10:12:39.454',
        name: '내가보냄',
        createId: 'test2',
        consultChannel: 1,
        consultChannelName: '협진 일정 요청',
        deadlineDatetime: '2022-03-13 16:19:42',
        consultConfirm: 'Y',
        isentState: 1,
        replyCount: 0,
        unconfirmedReplyCount: 2,
        memberInfoList: [
            {
                consultId: 'test2_2022-03-08T10:12:39.454',
                orderNo: 1,
                doctorId: 'test1',
                doctorName: '의사1',
                doctorLevel: 0,
                doctorLevelName: '교수님',
                replyState: null,
                doctorClass: 0,
                doctorClassName: '일반외과',
                remoteState: 'Y',
            },
            {
                consultId: 'test2_2022-03-08T10:12:39.454',
                orderNo: 2,
                doctorId: 'test3',
                doctorName: '의사3',
                doctorLevel: 0,
                doctorLevelName: '교수님',
                replyState: null,
                doctorClass: 0,
                doctorClassName: '일반외과',
                remoteState: 'Y',
            },
        ],
    },
    {
        consultId: 'test1_2022-03-08T10:02:16.218',
        name: '의사2',
        createId: 'test1',
        consultChannel: 1,
        consultChannelName: '협진 일정 요청',
        deadlineDatetime: '2022-03-10 12:00:00',
        consultConfirm: 'N',
        isentState: 0,
        replyCount: 1,
        unconfirmedReplyCount: 1,
        memberInfoList: [
            {
                consultId: 'test1_2022-03-08T10:02:16.218',
                orderNo: 1,
                doctorId: 'test2',
                doctorName: '의사2',
                doctorLevel: 0,
                doctorLevelName: '교수님',
                replyState: 'N',
                doctorClass: 0,
                doctorClassName: '일반외과',
                remoteState: 'N',
            },
            {
                consultId: 'test1_2022-03-08T10:02:16.218',
                orderNo: 2,
                doctorId: 'test3',
                doctorName: '의사3',
                doctorLevel: 0,
                doctorLevelName: '교수님',
                replyState: null,
                doctorClass: 0,
                doctorClassName: '일반외과',
                remoteState: 'N',
            },
        ],
    },
];
